name: Deploy to GitHub Pages

on:
  push:
    branches:
      - main # Adjust this to your deployment branch if different

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      # Checkout the repository
      - name: Checkout code
        uses: actions/checkout@v3

      # Setup Node.js
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18 # Adjust this to your required Node.js version

      # Install dependencies
      - name: Install dependencies
        run: npm install

      # Run predeploy script
      - name: Run predeploy script
        run: npm run predeploy

      # Run custom script
      - name: Run pages.js script
        run: node scripts/pages.js mm-camelcase main

      # Deploy to GitHub Pages
      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./out # Adjust this to your build output directory
